insert into user (email,password,nickname,phone,birthdate,resign,loginstate,role) values
('abc@naver.com','abc123!','닉네임','01011111111','000101','N','Y','USER'),
('aaa@naver.com','abc123!','고죠사토루','01011111111','990101','N','Y','USER'),
('bbb@naver.com','abc123!','고길동','01011111111','990101','N','Y','USER'),
('ccc@naver.com','abc123!','프리렌','01011111111','990101','N','Y','USER');

INSERT into menu (category,name,menu_ename,menu_price,menu_explain,menu_imgurl) VALUES
('goods', 'JNO 하우스 보온병', 'JNO House Thermos', 5000, '고급스러운 디자인의 보온병','image/상품/보온병/JNO 하우스 보온병.jpg'),
('goods', '스탠리 하우스 보온병', 'Stanley House Thermos', 5000, '견고한 스탠리 브랜드 보온병','image/상품/보온병/스탠리 하우스 보온병.jpg'),
('goods', 'JNM 하우스 보온병', 'JNM House Thermos', 5000, '실용적인 JNM 브랜드 보온병','image/상품/보온병/JNM 하우스 보온병.jpg'),
('goods', 'JNX 그린 워드마크 보온병', 'JNX Green Wordmark Thermos', 5000, '그린 색상 로고 보온병','image/상품/보온병/JNX 그린 워드마크 보온병.jpg'),
('goods', 'SS 블랙 앤 골드 스탠리 보온병', 'SS Black and Gold Stanley Thermos', 5000, '블랙과 골드 조합의 보온병','image/상품/보온병/SS 블랙 앤 골드 스탠리 보온병.jpg'),
('goods', '리유저블 & 글라스 세트', 'Reusable & Glass Set', 5000, '재사용 가능한 유리 세트','image/상품/선물세트/리유저블 & 글라스 세트.jpg'),
('goods', '리유저블 & 머그 세트', 'Reusable & Mug Set', 5000, '재사용 가능한 머그 세트','image/상품/선물세트/리유저블 & 머그 세트.jpg'),
('goods', '우리 쌀 파우더', 'Our Rice Powder', 5000, '국내산 쌀로 만든 파우더','image/상품/선물세트/우리 쌀 파우더.jpg'),
('goods', '우리 쑥 파우더', 'Our Mugwort Powder', 5000, '국내산 쑥으로 만든 파우더','image/상품/선물세트/우리 쑥 파우더.jpg'),
('goods', 'SS 그린 사이렌 케틀', 'SS Green Siren Kettle', 5000, '그린 색상 사이렌 디자인 케틀','image/상품/커피 용품/SS 그린 사이렌 케틀.jpg'),
('goods', '사이렌 고케틀', 'Siren Go Kettle', 5000, '고급스러운 사이렌 디자인 케틀','image/상품/커피 용품/사이렌 고케틀.jpg'),
('goods', '사이렌 레버 드리퍼', 'Siren Lever Dripper', 5000, '레버 방식의 사이렌 드리퍼','image/상품/커피 용품/사이렌 레버 드리퍼.jpg'),
('goods', '사이렌 밀크포머&컵', 'Siren Milk Frother & Cup', 5000, '밀크포머와 컵 세트','image/상품/커피 용품/사이렌 밀크포머&컵.jpg'),
('goods', '우드 핸들 글라스 서버', 'Wood Handle Glass Server', 5000, '나무 손잡이의 유리 서버','image/상품/커피 용품/우드 핸들 글라스 서버.jpg'),
('goods', '크림 컴프레소', 'Cream Compressed Coffee', 5000, '진한 크림의 컴프레소','image/상품/커피 용품/크림 컴프레소.jpg'),
('beverage', '라이트 핑크 자몽 피지오', 'Light Pink Grapefruit Phizzo', 5000, '핑크 자몽 맛 음료','image/음료/스타벅스 피지오/라이트 핑크 자몽 피지오.jpg'),
('beverage', '레드 애플 피지오', 'Red Apple Phizzo', 5000, '상큼한 레드 애플 맛 음료','image/음료/스타벅스 피지오/레드 애플 피지오.jpg'),
('beverage', '아이스크림 레드 애플 피지오', 'Ice Cream Red Apple Phizzo', 5000, '아이스크림과 애플 음료','image/음료/스타벅스 피지오/아이스크림 레드 애플 피지오.jpg'),
('beverage', '여수 바다 자몽 피지오', 'Yeosu Sea Grapefruit Phizzo', 5000, '여수 바다를 닮은 자몽 음료','image/음료/스타벅스 피지오/여수 바다 자몽 피지오.jpg'),
('beverage', '유자 패션 피지오', 'Yuzu Passion Phizzo', 5000, '유자와 패션후르츠 맛 음료','image/음료/스타벅스 피지오/유자 패션 피지오.jpg'),
('beverage', '제주팔삭 셔벗 피지오', 'Jeju Palshark Sherbet Phizzo', 5000, '제주 특산 셔벗 음료','image/음료/스타벅스 피지오/제주팔삭 셔벗 피지오.jpg'),
('beverage', '제주팔삭 피지오', 'Jeju Palshark Phizzo', 5000, '제주산 팔삭 과일 음료','image/음료/스타벅스 피지오/제주팔삭 피지오.jpg'),
('beverage', '쿨 라임 피지오', 'Cool Lime Phizzo', 5000, '시원한 라임 맛 음료','image/음료/스타벅스 피지오/쿨 라임 피지오.jpg'),
('beverage', '피치 딸기 피지오', 'Peach Strawberry Phizzo', 5000, '복숭아와 딸기 맛 음료','image/음료/스타벅스 피지오/피치 딸기 피지오.jpg'),
('beverage', '라벤더 카페 브레베.png', 'Lavender Cafe Breve', 5000, '라벤더 향의 브레베','image/음료/에스프레소/라벤더 카페 브레베.png'),
('coffee', '바닐라 빈 라떼', 'Vanilla Bean Latte', 5000, '바닐라 빈을 넣은 라떼','image/음료/에스프레소/바닐라 빈 라떼.jpg'),
('coffee', '바닐라 플랫 화이트', 'Vanilla Flat White', 5000, '부드러운 바닐라 플랫 화이트','image/음료/에스프레소/바닐라 플랫 화이트.jpg'),
('coffee', '사케라또 아포가토', 'Shakerato Affogato', 5000, '에스프레소를 부은 아이스크림','image/음료/에스프레소/사케라또 아포가토.jpg'),
('coffee', '슈크림 라떼', 'Cream Puff Latte', 5000, '크림이 듬뿍 들어간 라떼','image/음료/에스프레소/슈크림 라떼.jpg'),
('coffee', '스타벅스 돌체 라떼', 'Starbucks Dolce Latte', 5000, '달콤한 스타벅스 돌체 라떼','image/음료/에스프레소/스타벅스 돌체 라떼.jpg'),
('coffee', '스파클링 시트러스 에스프레소', 'Sparkling Citrus Espresso', 5000, '탄산과 시트러스 맛 에스프레소','image/음료/에스프레소/스파클링 시트러스 에스프레소.jpg'),
('coffee', '에스프레소', 'Espresso', 5000, '진한 에스프레소 커피','image/음료/에스프레소/에스프레소.jpg'),
('coffee', '카라멜 마키아또', 'Caramel Macchiato', 5000, '카라멜 시럽이 들어간 마키아또','image/음료/에스프레소/카라멜 마키아또.jpg'),
('coffee', '카페 라떼', 'Cafe Latte', 5000, '부드러운 우유가 들어간 라떼','image/음료/에스프레소/카페 라떼.jpg'),
('coffee', '카페 모카', 'Cafe Mocha', 5000, '초콜릿 시럽과 에스프레소가 들어간 모카','image/음료/에스프레소/카페 모카.jpg'),
('coffee', '카푸치노', 'Cappuccino', 5000, '거품 많은 이탈리아식 커피','image/음료/에스프레소/카푸치노.jpg'),
('coffee', '커피 스타벅스 더블 샷', 'Coffee Starbucks Doubleshot', 5000, '진한 더블 샷 커피','image/음료/에스프레소/커피 스타벅스 더블 샷.jpg'),
('coffee', '클래식 민트 모카', 'Classic Mint Mocha', 5000, '민트와 초콜릿이 조화된 모카','image/음료/에스프레소/클래식 민트 모카.jpg'),
('coffee', '클래식 아포가토', 'Classic Affogato', 5000, '아이스크림 위에 에스프레소','image/음료/에스프레소/클래식 아포가토.jpg'),
('coffee', '헤이즐넛 스타벅스 더블 샷', 'Hazelnut Starbucks Doubleshot', 5000, '헤이즐넛 향 더블 샷 커피','image/음료/에스프레소/헤이즐넛 스타벅스 더블 샷.jpg'),
('coffee', '화이트 초콜릿 모카', 'White Chocolate Mocha', 5000, '화이트 초콜릿 맛 모카','image/음료/에스프레소/화이트 초콜릿 모카.jpg'),
('beverage', '돌체 블랙 밀크 티', 'Dolce Black Milk Tea', 5000, '달콤한 블랙 밀크 티','image/음료/티(티바나)/돌체 블랙 밀크 티.jpg'),
('beverage', '레드 파워 패션 티', 'Red Power Passion Tea', 5000, '패션후르츠 향의 레드 티','image/음료/티(티바나)/레드 파워 패션 티.jpg'),
('beverage', '레몬 캐모마일 블렌드 티', 'Lemon Chamomile Blend Tea', 5000, '레몬과 캐모마일 블렌드 티','image/음료/티(티바나)/레몬 캐모마일 블렌드 티.jpg'),
('beverage', '말차 티라미수 라떼', 'Matcha Tiramisu Latte', 5000, '티라미수 맛 말차 라떼','image/음료/티(티바나)/말차 티라미수 라떼.jpg'),
('beverage', '민트 블렌드 티', 'Mint Blend Tea', 5000, '상쾌한 민트 블렌드 티','image/음료/티(티바나)/민트 블렌드 티.jpg'),
('beverage', '스노우 말차 라떼', 'Snow Matcha Latte', 5000, '눈처럼 부드러운 말차 라떼','image/음료/티(티바나)/스노우 말차 라떼.jpg'),
('beverage', '얼 그레이 티', 'Earl Grey Tea', 5000, '베르가못 향의 홍차','image/음료/티(티바나)/얼 그레이 티.jpg'),
('beverage', '유스베리 티', 'Youthberry Tea', 5000, '상큼한 베리 맛 티','image/음료/티(티바나)/유스베리 티.jpg'),
('beverage', '유자 민트 티', 'Yuzu Mint Tea', 5000, '유자와 민트가 어우러진 티','image/음료/티(티바나)/유자 민트 티.jpg'),
('beverage', '잉글리쉬 브렉퍼스트 티', 'English Breakfast Tea', 5000, '전통적인 영국식 아침 티','image/음료/티(티바나)/잉글리쉬 브렉퍼스트 티.jpg'),
('beverage', '제주 말차 라떼', 'Jeju Matcha Latte', 5000, '제주산 말차가 들어간 라떼','image/음료/티(티바나)/제주 말차 라떼.jpg'),
('beverage', '차이 티 라떼', 'Chai Tea Latte', 5000, '향신료가 듬뿍 들어간 차이 라떼','image/음료/티(티바나)/차이 티 라떼.jpg'),
('beverage', '캐모마일 블렌드 티', 'Chamomile Blend Tea', 5000, '진정 효과의 캐모마일 티','image/음료/티(티바나)/캐모마일 블렌드 티.jpg'),
('beverage', '히비스커스 블렌드 티', 'Hibiscus Blend Tea', 5000, '상큼한 히비스커스 블렌드 티','image/음료/티(티바나)/히비스커스 블렌드 티.jpg'),
('beverage', '에스프레소 프라푸치노', 'Espresso Frappuccino', 5000, '에스프레소가 들어간 프라푸치노','image/음료/프라푸치노/에스프레소 프라푸치노.jpg'),
('beverage', '자바 칩 프라푸치노', 'Java Chip Frappuccino', 5000, '초콜릿 칩이 들어간 프라푸치노','image/음료/프라푸치노/자바 칩 프라푸치노.jpg'),
('beverage', '제주 말차 크림 프라푸치노', 'Jeju Matcha Cream Frappuccino', 5000, '제주 말차 크림 프라푸치노','image/음료/프라푸치노/제주 말차 크림 프라푸치노.jpg'),
('beverage', '카라멜 프라푸치노', 'Caramel Frappuccino', 5000, '카라멜 시럽 프라푸치노','image/음료/프라푸치노/카라멜 프라푸치노.jpg'),
('food', '거문 오름 크루아상', 'Geomun Oreum Croissant', 5000, '거문 오름을 닮은 크루아상','image/푸드/브레드/거문 오름 크루아상.jpg'),
('food', '미니 리프 파이', 'Mini Leaf Pie', 5000, '작은 잎 모양의 파이','image/푸드/브레드/미니 리프 파이.jpg'),
('food', '미니 클래식 스콘', 'Mini Classic Scone', 5000, '작은 클래식 스콘','image/푸드/브레드/미니 클래식 스콘.jpg'),
('food', '바질 치즈 포카치아', 'Basil Cheese Focaccia', 5000, '바질과 치즈가 들어간 포카치아','image/푸드/브레드/바질 치즈 포카치아.jpg'),
('food', '바질 토마토 크림치즈 베이글', 'Basil Tomato Cream Cheese Bagel', 5000, '바질, 토마토, 크림치즈 베이글','image/푸드/브레드/바질 토마토 크림치즈 베이글.jpg'),
('food', '블루밍 체리블라썸 세트', 'Blooming Cherry Blossom Set', 5000, '체리블라썸 세트','image/푸드/브레드/블루밍 체리블라썸 세트.jpg'),
('food', '뺑 오 쇼콜라', 'Pain au Chocolat', 5000, '초콜릿이 듬뿍 들어간 페이스트리','image/푸드/브레드/뺑 오 쇼콜라.jpg'),
('food', '소금빵', 'Salt Bread', 5000, '소금이 들어간 빵','image/푸드/브레드/소금빵.jpg'),
('food', '스모크드 소시지 브레드', 'Smoked Sausage Bread', 5000, '훈제 소시지가 들어간 빵','image/푸드/브레드/스모크드 소시지 브레드.jpg'),
('food', '연유 밀크모닝', 'Condensed Milk Morning Roll', 5000, '달콤한 연유 맛의 빵','image/푸드/브레드/연유 밀크모닝.jpg'),
('food', '오름 치즈 케이츄리', 'Oreum Cheese Quiche', 5000, '치즈가 들어간 퀴시','image/푸드/브레드/오름 치즈 케이츄리.jpg'),
('food', '올래 미니 크루아상', 'Ollae Mini Croissant', 5000, '작은 사이즈의 미니 크루아상','image/푸드/브레드/올래 미니 크루아상.jpg'),
('food', '주상절리 파이', 'Columnar Joint Pie', 5000, '주상절리를 닮은 파이','image/푸드/브레드/주상절리 파이.jpg'),
('food', '체리 품은 큐브 브레드', 'Cherry Cube Bread', 5000, '체리가 들어간 큐브 모양 빵','image/푸드/브레드/체리 품은 큐브 브레드.jpg'),
('food', '초콜릿 월넛 브레드', 'Chocolate Walnut Bread', 5000, '초콜릿과 호두가 들어간 빵','image/푸드/브레드/초콜릿 월넛 브레드.jpg'),
('food', '퀸아망 체리크림 샌드', 'Kouign Amann Cherry Cream Sandwich', 5000, '체리크림이 샌드된 퀸아망','image/푸드/브레드/퀸아망 체리크림 샌드.jpg'),
('food', '크림치즈 브리오슈 보스톡', 'Cream Cheese Brioche Bostock', 5000, '크림치즈가 들어간 브리오슈','image/푸드/브레드/크림치즈 브리오슈 보스톡.jpg'),
('food', '클래식 스콘', 'Classic Scone', 5000, '전통적인 스콘','image/푸드/브레드/클래식 스콘.jpg'),
('food', '탕종 플레인 베이글', 'Tangzhong Plain Bagel', 5000, '부드러운 플레인 베이글','image/푸드/브레드/탕종 플레인 베이글.jpg'),
('food', '포테이토 어니언 크림치즈 베이글', 'Potato Onion Cream Cheese Bagel', 5000, '감자와 양파, 크림치즈 베이글','image/푸드/브레드/포테이토 어니언 크림치즈 베이글.jpg'),
('food', '피넛 쑥 떡 스콘', 'Peanut Mugwort Rice Cake Scone', 5000, '피넛과 쑥이 들어간 떡 스콘','image/푸드/브레드/피넛 쑥 떡 스콘.jpg'),
('food', '피스타치오 핑크 롤', 'Pistachio Pink Roll', 5000, '피스타치오와 핑크 롤','image/푸드/브레드/피스타치오 핑크 롤.jpg'),
('food', '하트 파이', 'Heart Pie', 5000, '하트 모양의 파이','image/푸드/브레드/하트 파이.jpg'),
('food', '한 입에 쏙 치즈 꿀 볼', 'Bite-sized Cheese Honey Ball', 5000, '치즈와 꿀이 들어간 볼','image/푸드/브레드/한 입에 쏙 치즈 꿀 볼.jpg'),
('food', 'The 촉촉 초콜릿 생크림 케이크', 'The Moist Chocolate Fresh Cream Cake', 5000, '촉촉한 초콜릿 생크림 케이크','image/푸드/케이크/The 촉촉 초콜릿 생크림 케이크.jpg'),
('food', '꿀 고구마 생크림 케이크', 'Honey Sweet Potato Fresh Cream Cake', 5000, '고구마 생크림 케이크','image/푸드/케이크/꿀 고구마 생크림 케이크.jpg'),
('food', '당근 현무암 케이크', 'Carrot Basalt Cake', 5000, '당근과 현무암 모양의 케이크','image/푸드/케이크/당근 현무암 케이크.jpg'),
('food', '돔 피칸 타르트', 'Dome Pecan Tart', 5000, '돔 모양의 피칸 타르트','image/푸드/케이크/돔 피칸 타르트.jpg'),
('food', '딸기 생크림 케이크', 'Strawberry Fresh Cream Cake', 5000, '딸기가 들어간 생크림 케이크','image/푸드/케이크/딸기 생크림 케이크.jpg'),
('food', '딸기 초코 쏙 생크림 케이크', 'Strawberry Chocolate Fresh Cream Cake', 5000, '딸기와 초코 생크림 케이크','image/푸드/케이크/딸기 초코 쏙 생크림 케이크.jpg'),
('food', '라즈베리 쇼콜라', 'Raspberry Chocolate', 5000, '라즈베리가 들어간 초콜릿','image/푸드/케이크/라즈베리 쇼콜라.jpg'),
('food', '레드벨벳 크림치즈 케이크', 'Red Velvet Cream Cheese Cake', 5000, '레드벨벳과 크림치즈 케이크','image/푸드/케이크/레드벨벳 크림치즈 케이크.jpg'),
('food', '마스카포네 티라미수', 'Mascarpone Tiramisu', 5000, '마스카포네 치즈가 들어간 티라미수','image/푸드/케이크/마스카포네 티라미수.jpg'),
('food', '바스크 치즈 케이크', 'Basque Cheesecake', 5000, '부드러운 바스크 치즈 케이크','image/푸드/케이크/바스크 치즈 케이크.jpg'),
('food', '베어리스타 우유 생크림 케이크', 'Bearista Milk Fresh Cream Cake', 5000, '우유 생크림 케이크','image/푸드/케이크/베어리스타 우유 생크림 케이크.jpg'),
('food', '블루베리 쿠키 치즈 케이크', 'Blueberry Cookie Cheesecake', 5000, '블루베리와 쿠키 치즈 케이크','image/푸드/케이크/블루베리 쿠키 치즈 케이크.jpg'),
('food', '세븐 레이어 가나슈 케이크', 'Seven Layer Ganache Cake', 5000, '7층 가나슈 케이크','image/푸드/케이크/세븐 레이어 가나슈 케이크.jpg'),
('food', '슈크림 가득 바움쿠헨', 'Cream Puff Baumkuchen', 5000, '슈크림이 가득한 바움쿠헨','image/푸드/케이크/슈크림 가득 바움쿠헨.jpg'),
('food', '슈크림 딸기 블루밍 케이크', 'Cream Puff Strawberry Blooming Cake', 5000, '딸기 블루밍 케이크','image/푸드/케이크/슈크림 딸기 블루밍 케이크.jpg'),
('food', '스틱 에그 타르트', 'Stick Egg Tart', 5000, '스틱 형태의 에그 타르트','image/푸드/케이크/스틱 에그 타르트.jpg'),
('food', '제주 녹차 생크림 롤', 'Jeju Green Tea Fresh Cream Roll', 5000, '제주 녹차가 들어간 생크림 롤','image/푸드/케이크/제주 녹차 생크림 롤.jpg'),
('food', '제주 땅콩 생크림 롤', 'Jeju Peanut Fresh Cream Roll', 5000, '제주 땅콩이 들어간 생크림 롤','image/푸드/케이크/제주 땅콩 생크림 롤.jpg'),
('food', '크레이프 에멘탈 치즈 케이크', 'Crepe Emmental Cheesecake', 5000, '에멘탈 치즈 크레이프 케이크','image/푸드/케이크/크레이프 에멘탈 치즈 케이크.jpg'),
('food', '클라우드 치즈 케이크', 'Cloud Cheesecake', 5000, '부드러운 클라우드 치즈 케이크','image/푸드/케이크/클라우드 치즈 케이크.jpg'),
('food', '클래식 블루베리 치즈 케이크', 'Classic Blueberry Cheesecake', 5000, '클래식 블루베리 치즈 케이크','image/푸드/케이크/클래식 블루베리 치즈 케이크.jpg');

INSERT INTO home_ad (ad_head, ad_content, ad_upload_time, ad_due_date, category, image_url) VALUES
('회원가입안내', '회원가입안내 내용', NOW(), DATE_ADD(NOW(), INTERVAL 10 DAY), 1, 'image/HomeSigninAd/2024-09-11.jpeg'),
('이벤트1', '혜택1', NOW(), DATE_ADD(NOW(), INTERVAL 7 DAY), 2, 'image/HomeEvent/2024-03-28 4월 프로모션.jpg'),
('이벤트2', '혜택2', NOW(), DATE_ADD(NOW(), INTERVAL 7 DAY), 2, 'image/HomeEvent/2024-04-18 제주 지역 리유저블 컵 이벤트.jpg');

INSERT into recommend (menu_category,menu_name,menu_ename,menu_price,menu_explain,menu_image_url) VALUES
('beverage', '제주팔삭 셔벗 피지오', 'Jeju Palshark Sherbet Phizzo', 5000, '제주 특산 셔벗 음료','image/음료/스타벅스 피지오/제주팔삭 셔벗 피지오.jpg'),
('beverage', '제주팔삭 피지오', 'Jeju Palshark Phizzo', 5000, '제주산 팔삭 과일 음료','image/음료/스타벅스 피지오/제주팔삭 피지오.jpg'),
('coffee', '바닐라 빈 라떼', 'Vanilla Bean Latte', 5000, '바닐라 빈을 넣은 라떼','image/음료/에스프레소/바닐라 빈 라떼.jpg'),
('coffee', '카페 라떼', 'Cafe Latte', 5000, '부드러운 우유가 들어간 라떼','image/음료/에스프레소/카페 라떼.jpg'),
('coffee', '카페 모카', 'Cafe Mocha', 5000, '초콜릿 시럽과 에스프레소가 들어간 모카','image/음료/에스프레소/카페 모카.jpg'),
('coffee', '카푸치노', 'Cappuccino', 5000, '거품 많은 이탈리아식 커피','image/음료/에스프레소/카푸치노.jpg'),
('beverage', '잉글리쉬 브렉퍼스트 티', 'English Breakfast Tea', 5000, '전통적인 영국식 아침 티','image/음료/티(티바나)/잉글리쉬 브렉퍼스트 티.jpg'),
('food', '꿀 고구마 생크림 케이크', 'Honey Sweet Potato Fresh Cream Cake', 5000, '고구마 생크림 케이크','image/푸드/케이크/꿀 고구마 생크림 케이크.jpg'),
('food', '딸기 생크림 케이크', 'Strawberry Fresh Cream Cake', 5000, '딸기가 들어간 생크림 케이크','image/푸드/케이크/딸기 생크림 케이크.jpg'),
('food', '딸기 초코 쏙 생크림 케이크', 'Strawberry Chocolate Fresh Cream Cake', 5000, '딸기와 초코 생크림 케이크','image/푸드/케이크/딸기 초코 쏙 생크림 케이크.jpg');