insert into user (email,password,nickname,phone,birthdate,resign,loginstate,role) values
('abc@naver.com','abc123!','닉네임','01011111111','000101','N','Y','USER'),
('aaa@naver.com','abc123!','고죠사토루','01011111111','990101','N','Y','USER'),
('bbb@naver.com','abc123!','고길동','01011111111','990101','N','Y','USER'),
('ccc@naver.com','abc123!','프리렌','01011111111','990101','N','Y','USER');

INSERT into menu (category,name,menu_ename,menu_price,menu_imgurl,menu_bannerimgurl) VALUES
('coffee','돌체','englishname',5000,'image/음료/스타벅스 리프레셔/딸기 아사이 레모네이드 스타벅스 리프레셔.jpg','image/banner/빽다방.jpg'),
('coffee','바닐라 크림 콜드 브루','englishname',5000,'image/음료/스타벅스 리프레셔/딸기 아사이 레모네이드 스타벅스 리프레셔.jpg', 'image/banner/빽다방.jpg'),
('coffee','콜드 브루 몰트','englishname',5000,'image/음료/스타벅스 리프레셔/딸기 아사이 레모네이드 스타벅스 리프레셔.jpg', 'image/banner/빽다방.jpg'),
('coffee','클래식 아포가토','englishname',5000,'image/음료/스타벅스 리프레셔/딸기 아사이 레모네이드 스타벅스 리프레셔.jpg', 'image/banner/빽다방.jpg'),
('coffee','카라멜 프라푸치노','englishname',5000,'image/음료/스타벅스 리프레셔/딸기 아사이 레모네이드 스타벅스 리프레셔.jpg', 'image/banner/빽다방.jpg'),
('coffee','자바 칩 프라푸치노','englishname',5000,'image/음료/스타벅스 리프레셔/딸기 아사이 레모네이드 스타벅스 리프레셔.jpg', 'image/banner/빽다방.jpg'),
('coffee','아이스 카페 모카','englishname',5000,'image/음료/스타벅스 리프레셔/딸기 아사이 레모네이드 스타벅스 리프레셔.jpg', 'image/banner/빽다방.jpg'),
('coffee','딸기 딜라이트 요거트 블렌디드','englishname',5000,'image/음료/스타벅스 리프레셔/딸기 아사이 레모네이드 스타벅스 리프레셔.jpg', 'image/banner/빽다방.jpg'),
('coffee','스노우 말차 라떼','englishname',5000,'image/음료/스타벅스 리프레셔/딸기 아사이 레모네이드 스타벅스 리프레셔.jpg', 'image/banner/빽다방.jpg'),
('coffee','아이스 스노우 말차 라떼','englishname',5000,'image/음료/스타벅스 리프레셔/딸기 아사이 레모네이드 스타벅스 리프레셔.jpg', 'image/banner/빽다방.jpg'),
('beverage','민트 블렌드 티','englishname',5000,'image/음료/스타벅스 주스(병음료)/햇사과 주스 591ML.jpg','image/banner/빽다방.jpg'),
('beverage','아이스 민트 블렌드 티','englishname',5000,'image/음료/스타벅스 주스(병음료)/햇사과 주스 591ML.jpg', 'image/banner/빽다방.jpg'),
('beverage','아이스 얼 그레이 티','englishname',5000,'image/음료/스타벅스 주스(병음료)/햇사과 주스 591ML.jpg', 'image/banner/빽다방.jpg'),
('beverage','얼 그레이 티','englishname',5000,'image/음료/스타벅스 주스(병음료)/햇사과 주스 591ML.jpg', 'image/banner/빽다방.jpg'),
('beverage','아이스 유자 민트 티','englishname',5000,'image/음료/스타벅스 주스(병음료)/햇사과 주스 591ML.jpg', 'image/banner/빽다방.jpg'),
('beverage','레몬 진저 클렌즈 190ML','englishname',5000,'image/음료/스타벅스 주스(병음료)/햇사과 주스 591ML.jpg', 'image/banner/빽다방.jpg'),
('beverage','케일 클렌즈 190ML','englishname',5000,'image/음료/스타벅스 주스(병음료)/햇사과 주스 591ML.jpg', 'image/banner/빽다방.jpg'),
('beverage','딸기주스 190ML','englishname',5000,'image/음료/스타벅스 주스(병음료)/햇사과 주스 591ML.jpg', 'image/banner/빽다방.jpg'),
('beverage','망고주스 190ML','englishname',5000,'image/음료/스타벅스 주스(병음료)/햇사과 주스 591ML.jpg', 'image/banner/빽다방.jpg'),
('beverage','스타 루비 자몽 스위트 190ML','englishname',5000,'image/음료/스타벅스 주스(병음료)/햇사과 주스 591ML.jpg', 'image/banner/빽다방.jpg'),
('food','피스타치오 핑크 롤','englishname',5000,'image/푸드/샌드위치 & 샐러드/햄&루꼴라 올리브 샌드위치.jpg','image/banner/빽다방.jpg'),
('food','바질 토마토 크림치즈 베이글','englishname',5000,'image/푸드/샌드위치 & 샐러드/햄&루꼴라 올리브 샌드위치.jpg', 'image/banner/빽다방.jpg'),
('food','탕종 블루베리 베이글','englishname',5000,'image/푸드/샌드위치 & 샐러드/햄&루꼴라 올리브 샌드위치.jpg', 'image/banner/빽다방.jpg'),
('food','탕종 파마산 치즈 베이글','englishname',5000,'image/푸드/샌드위치 & 샐러드/햄&루꼴라 올리브 샌드위치.jpg', 'image/banner/빽다방.jpg'),
('food','탕종 플레인 베이글','englishname',5000,'image/푸드/샌드위치 & 샐러드/햄&루꼴라 올리브 샌드위치.jpg', 'image/banner/빽다방.jpg'),
('food','7 레이어 가나슈 케이크','englishname',5000,'image/푸드/샌드위치 & 샐러드/햄&루꼴라 올리브 샌드위치.jpg', 'image/banner/빽다방.jpg'),
('food','딸기 생크림 케이크','englishname',5000,'image/푸드/샌드위치 & 샐러드/햄&루꼴라 올리브 샌드위치.jpg', 'image/banner/빽다방.jpg'),
('food','치킨 & 머쉬룸 멜팅 치즈 샌드위치','englishname',5000,'image/푸드/샌드위치 & 샐러드/햄&루꼴라 올리브 샌드위치.jpg', 'image/banner/빽다방.jpg'),
('food','치킨 베이컨 랩','englishname',5000,'image/푸드/샌드위치 & 샐러드/햄&루꼴라 올리브 샌드위치.jpg', 'image/banner/빽다방.jpg'),
('goods','사이렌 클래식 그린 머그 355ml','englishname',5000,'image/상품/글라스/리저브 골드 핸들 글라스 473ml.jpg','image/banner/빽다방.jpg'),
('goods','파스텔 블루 텀블러 473ml','englishname',5000,'image/상품/글라스/리저브 골드 핸들 글라스 473ml.jpg', 'image/banner/빽다방.jpg'),
('goods','파스텔 핑크 텀블러 473ml','englishname',5000,'image/상품/글라스/리저브 골드 핸들 글라스 473ml.jpg', 'image/banner/빽다방.jpg'),
('goods','SS 나수 하우스 텀블러 355ml','englishname',5000,'image/상품/글라스/리저브 골드 핸들 글라스 473ml.jpg', 'image/banner/빽다방.jpg'),
('goods','(c)SS 콩코드 하우스 텀블러 591ml','englishname',5000,'image/상품/글라스/리저브 골드 핸들 글라스 473ml.jpg', 'image/banner/빽다방.jpg'),
('goods','SS 코리아 크림 텀블러 473ml','englishname',5000,'image/상품/글라스/리저브 골드 핸들 글라스 473ml.jpg', 'image/banner/빽다방.jpg'),
('goods','스타벅스 그린 멀티백','englishname',5000,'image/상품/글라스/리저브 골드 핸들 글라스 473ml.jpg', 'image/banner/빽다방.jpg'),
('goods','(c)스타벅스 하우스 장우산','englishname',5000,'image/상품/글라스/리저브 골드 핸들 글라스 473ml.jpg', 'image/banner/빽다방.jpg'),
('goods','(b)틴케이스 문구 세트','englishname',5000,'image/상품/글라스/리저브 골드 핸들 글라스 473ml.jpg', 'image/banner/빽다방.jpg'),
('goods','(c)JNO 하우스 보온병 500ml','englishname',5000,'image/상품/글라스/리저브 골드 핸들 글라스 473ml.jpg', 'image/banner/빽다방.jpg');

INSERT INTO home_ad (ad_head, ad_content, ad_upload_time, ad_due_date, category, image_url) VALUES
('회원가입안내', '회원가입안내 내용', NOW(), DATE_ADD(NOW(), INTERVAL 10 DAY), 1, 'image/HomeSigninAd/2024-09-11.jpeg'),
('이벤트1', '혜택1', NOW(), DATE_ADD(NOW(), INTERVAL 7 DAY), 2, 'image/HomeEvent/2024-03-28 4월 프로모션.jpg'),
('이벤트2', '혜택2', NOW(), DATE_ADD(NOW(), INTERVAL 7 DAY), 2, 'image/HomeEvent/2024-04-18 제주 지역 리유저블 컵 이벤트.jpg');

